### ISSUE TITLE
UPDATE for IOS7

### ISSUE THREAD

**Issue by geogerar** [andrei200287/SAVideoRangeSlider#2]
Your tool is great but I have a small recomentation.
Can you please update it because with  IOS7 it functions providing the thubnails very very slowly!!!!

Thanks in advance

George Gerardis

**Comment by andrei200287** [comment]
Fixed.

**Comment by datibbaw** [comment]
I ran into a similar issue, but I've managed to solve it without having to use synchronous image grabbing; see also [this SO question](http://stackoverflow.com/questions/27124482/generating-thumbnail-bar-with-avassetimagegenerator); hope that helps :)
